name: 'Terraform'
on:
  push:
    branches:
      - main
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  TF_IN_AUTOMATION: true
  TF_WORKSPACE: -dev
  TF_BACKEND_PATH: dev.tfvars
  TF_VAR_tf_backend_bucket_name: terraform-vpc-state
  
  

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/checkout@v2
      - name: Configure AWS credential
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "us-west-1"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.3.2
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Init
        id: init 
        run: |
          cd terraform/create-ec2
          terraform init
          
      - name: Terraform Validate
        id: validate
        run: |
          cd terraform/create-ec2
          terraform validate -no-color
              
      - name: Terraform Plan
        id: plan
        run: |
          cd terraform/create-ec2
          terraform plan -no-color -input=false 
        continue-on-error: true

      - name: Terraform Apply
        run: |
          cd terraform/create-ec2
          terraform apply -auto-approve -input=false 

      # - name: Terraform destroy
      #   run: terraform destroy -auto-approve -input=false 
