name: 'Configure ec2'
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  ansible:
    name: 'Ansible'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run playbook
        uses: dawidd6/action-ansible-playbook@v2
        with:
          # Required, playbook filepath
          playbook: configure-ec2.yml
          # Optional, directory where playbooks live
          directory: ./
          # Optional, SSH private key
          key: ${{secrets.SSH_PRIVATE_KEY}}
          # Optional, literal inventory file contents
          inventory: |
            [all]
            example.com
