name: Run packer build on a template file

on:
  workflow_dispatch:
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          #aws_session_token: ${{ secrets.AWS_SESSION_TOKEN}}
          aws-region: us-west-1
      - run: |
          repo_name=${{ github.event.repository.name }}
          git config --global --add safe.directory /__w/$repo_name/$repo_name
          git_hash=$(git rev-parse --short "$GITHUB_SHA")
          echo "$SSH_KEY" > /__w/$repo_name/$repo_name/Ansible/id_rsa
          packer init .
          packer build .
          
          
          
        name: Run in container
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }} 