name: remote ssh command
on:
  workflow_dispatch:
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: 13.56.229.47
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        port: 22
        script: cd /home/ubuntu/manju && ls -a
